summit-webapp-themes/fancy-gold

components/PageMetaData/PageMetaData.tsx, components/ProductListingComponents/ProductListingMaster.tsx
Page Meta Data component added
=> fix:page metadata added

components/Navbar/HeaderCategories.tsx, components/Navbar/Navbar.tsx, styles/components/_header.scss
Navigate to Product listing from navbar
=> Navigate to Product listing from navbar

cards/ProductCard.tsx, components/HomePage/DisplayTags/DisplayTags.tsx, components/HomePage/DisplayTags/SliderSection.tsx, components/Skeleton/ProductCardSkeleton.tsx
#Description
- Product Card Skeleton fix.
- Code refactoring
=> Product card skeleton UI

components/Navbar/NavbarLoadingComponent.tsx, components/ProductDetailComponents/ProductDetailMaster.tsx, components/ProductListingComponents/FilterView/FIlterViewComponent.tsx, components/ProductListingComponents/FilterView/FilterViewLoadingComponent.tsx, components/ProductListingComponents/FilterView/FilterViewMaster.tsx, components/ProductListingComponents/FilterView/WebFilters.tsx, components/ProductListingComponents/ProductGridView/GridViewLoadingComponent.tsx, components/ProductListingComponents/ProductGridView/ProductGridViewMaster.tsx, components/ProductListingComponents/ProductGridView/ProductsGridView.tsx, components/ProductListingComponents/ProductListView/ListViewLoadingComponent.tsx, components/ProductListingComponents/ProductListView/ProductListViewMaster.tsx, components/ProductListingComponents/ProductListView/ProductsListView.tsx, components/ProductListingComponents/ProductListingMaster.tsx
1) Added skeleton in filter selection ,  grid , list view section of product listing page 
2) Modified navbar skeleton
=> Added skeleton in listing page - grid, list view

components/ProductDetailComponents/ProductDetails/BreadCrumbs.tsx, components/ProductListingComponents/ProductListingMaster.tsx, styles/components/_breadcrumb.scss, styles/globals.scss
=> Breadcrumbs UI added

_app.tsx
=> Bootstrap cdn link removed

cards/ProductCard.tsx, cards/ProductCardSkeleton.tsx, components/HomePage/Banner/Banner.tsx, components/HomePage/Banner/BannerSkeleton.tsx, components/HomePage/DisplayTags/DisplayTagLoadingComponnet.tsx, components/HomePage/DisplayTags/DisplayTags.tsx, components/HomePage/DisplayTags/SliderSection.tsx, components/HomePage/HomePage.tsx, components/Navbar/HeaderCategories.tsx, components/Navbar/Navbar.tsx, components/Navbar/NavbarLoadingComponent.tsx, components/ProductListingComponents/FilterView/FilterViewLoadingComponent.tsx, components/ProductListingComponents/FilterView/WebFilters.tsx, components/ProductListingComponents/ProductGridView/ProductGridViewMaster.tsx, components/ProductListingComponents/ProductGridView/ProductsGridView.tsx, components/ProductListingComponents/ProductListingMaster.tsx, styles/components/_header.scss, styles/components/_navbar.scss, styles/components/banner.module.scss, styles/components/displayTags.module.scss, styles/components/pagination.module.scss, styles/components/productCard.module.scss, styles/components/sliderSection.module.scss
Added banner section , skeleton navbar and home page UI fixes 
UI fixes in product card
=> Banner section API integration 

components/Navbar/HeaderCategories.tsx, components/Navbar/MobSideNavbar.tsx, components/Navbar/Navbar.tsx, styles/components/_header.scss, styles/components/header.module.scss, styles/components/mobNavbar.module.scss, styles/components/navbar.module.scss, styles/globals.scss
=> Added logout functionality

components/Cart/CartListing.tsx, components/Cart/CartProductDetail.tsx, components/Cart/SizeQtyTable.tsx, styles/components/cartProductDetail.module.scss
=> Cart page fixed

cards/ProductCard.tsx, components/ProductDetailComponents/ProductDetailDrawer/DrawerSkeleton.tsx, components/ProductDetailComponents/ProductDetailDrawer/ImageSkeleton.tsx, components/ProductDetailComponents/ProductDetailDrawer/ProductDetailDrawer.tsx, components/ProductDetailComponents/ProductDetailDrawer/ProductDetailInfo.tsx, components/ProductDetailComponents/ProductDetailMaster.tsx, components/ProductDetailComponents/ProductDetails/ProductDetails.tsx, components/ProductDetailComponents/ProductDetails/ProductVariants.tsx
- Add to cart drawer and product detail page skeleton
- variant loader
- wishlist icon change
=> Add to cart drawer skeleton

components/ProductDetailComponents/ProductDetailMaster.tsx, components/ProductDetailComponents/ProductDetails/PrevNextButtons.tsx, components/ProductDetailComponents/ProductDetails/ProductDetails.tsx, styles/components/productDetail.module.scss
- Prev next buttons
- Filter issue fixed
=> Issues fixed

components/BulkOrder/MarketOrderTable.tsx, components/ProductDetailComponents/ProductDetailDrawer/ProductDetailInfo.tsx, styles/components/productDetail.module.scss
1. **Weight Field Computation**  
- Implemented accurate weight field computation in the Add to Cart drawer and the Detail Page.  
2. **Bulk Market Order**  
- Updated input handling for bulk market orders to improve usability and functionality.  
Let me know if further adjustments are needed!
=> Weight computation in Add to cart Modal

components/Cart/CartProductDetail.tsx, components/ProductDetailComponents/ProductDetailDrawer/ProductDetailInfo.tsx, components/ProductDetailComponents/ProductDetails/ProductImage.tsx, components/ProductDetailComponents/ProductDetails/ProductVariants.tsx, styles/components/cartProductDetail.module.scss, styles/globals.scss
1. **Product Detail Page**  
- Implemented sorting for size and variant options to enhance user experience.  
2. **Cart Page**  
- Added BOM Factory Code display for better order clarity and management.  
Let me know if there are additional improvements needed!
=> Issues after live

components/ProductDetailComponents/ProductDetails/ProductDetails.tsx, components/ProductDetailComponents/ProductDetails/ProductImage.tsx, styles/globals.scss
1. **Magnified Image Gallery**  
- Added a magnified image gallery on the product detail page for enhanced image viewing and user experience.  
Let me know if further improvements are needed!
=> fix: magnified image gallery added

components/ProductDetailComponents/ProductDetailDrawer/ProductDetailDrawer.tsx, components/ProductDetailComponents/ProductDetails/ProductImage.tsx, styles/components/productCard.module.scss, styles/globals.scss
1. **Zoom-In Effect**  
- Increased the zoom-in effect for images on the Product Listing Page and Product Details Page for better visual inspection and user experience.  
Let me know if any further adjustments are needed!
=>  image zoom issue

components/CatalogListingComponents/CatalogListingMaster.tsx
1. **Catalog Master Component**  
- Added a Catalog Master component to serve as a centralized and reusable component for managing catalog-related functionality.  
Let me know if additional enhancements are needed!
=> fix: catalog master added

cards/ProductCard.tsx
1. **Product Card Update**  
- Added logic to display the net weight on the product card if the Level 2 category is `MANGALSUTRA`.  
Let me know if further refinements are needed!
=> fix: net weight for mangalsutra

components/ProductDetailComponents/ProductDetailDrawer/ProductDetailDrawer.tsx
1. **Product Detail Error**  
- Resolved the "Product Detail Not Found" error to ensure smooth navigation and accurate data display.  
Let me know if further refinements are required!
=> fix: product detail page details not found error

cards/ProductCard.tsx
1. **Product Card Update**  
- Added logic to display the net weight on the product card if the Level 2 category is `MANGALSUTRA`.  
Let me know if further refinements are needed!
=> fix: net wt for mangalsutra

cards/ProductCard.tsx, components/CatalogListingComponents/CatalogListingMaster.tsx, components/CatalogListingComponents/CatalogProductListingMaster.tsx, components/Navbar/Navbar.tsx, components/ProductListingComponents/ProductGridView/ProductGridViewMaster.tsx, styles/components/catalog.module.scss
1. **Default Page Handling**  
- Updated logic to set the default page to `1` if the `page` key is not found in the URL query parameters.  
2. **Catalog Listing**  
- Implemented the Catalog Listing page to display a list of catalogs efficiently.  
3. **Catalog Product Listing**  
- Added the Catalog Product Listing page to showcase products within a specific catalog.  
Let me know if any additional adjustments are needed!
=> Catalog listing and catalog product listing added

components/ProductDetailComponents/ProductDetailDrawer/ProductDetailInfo.tsx, components/ProductDetailComponents/ProductDetails/ProductVariants.tsx, styles/globals.scss
1. **Design Style as a Variant**  
- Added **Design Style** as a variant to better structure product variations.  
2. **Size Table Update**  
- Removed **Design Style** from the Size Table to maintain data consistency.  
=> Design style as variant

cards/OrderDetailCard.tsx
1. **Previous Behavior**  
- "Ready to Dispatch" and "Delete" buttons were displayed based on a specific condition.  
2. **New Update**  
- Added an additional condition:  
- If the status is **Accepted** or **WIP**, the buttons will now be visible.  
Let me know if any further refinements are needed!
=> Show delete and ready to dispatch buttons

components/ProductDetailComponents/ProductDetailDrawer/ProductDetailInfo.tsx, components/ProductDetailComponents/ProductDetails/ProductVariants.tsx, styles/globals.scss
1. **Design Style as a Variant**  
- Added **Design Style** as a variant to better structure product variations.  
2. **Size Table Update**  
- Removed **Design Style** from the Size Table to maintain data consistency.  
=> feat: added design style as a variant

cards/OrderDetailCard.tsx
1. **Pending Status Handling**  
- Added **Pending** status in order detail validation to improve order tracking and state management.  
=> fix: added pending status in order detail validation

components/ProductListingComponents/ProductGridView/ProductGridViewMaster.tsx
1. **Pagination Issue Resolved**  
- Fixed pagination to ensure proper navigation and data retrieval across pages.  
=> fix: pagination fixed

components/ProductListingComponents/ProductListingMaster.tsx, styles/components/filterSidebar.module.scss
**Problem**  
- Previously applied filters were getting cleared if new filters were applied before the page fully loaded.  
**Solution**  
- Disabled filter actions while the product listing API is in a loading or pending state to prevent filter clearing issues.  
Let me know if further improvements are needed!
=> Filters Issue fixed

components/ProductDetailComponents/ProductDetailDrawer/ProductDetailInfo.tsx
1. **Category-Based Sizing**  
- Added logic to dynamically populate **different sizes** based on the selected **category**.  
=> feat: dynamic sizes added according to category

components/ProductDetailComponents/ProductDetailDrawer/ProductDetailInfo.tsx
1. **Category-Based Sizing**  
- Added logic to dynamically populate **different sizes** based on the selected **category**.  
=> Update: Dynamic Size Handling  

components/ProductDetailComponents/ProductDetailDrawer/ProductDetailInfo.tsx
1. **Size Table Alignment Fixed**  
- Adjusted layout for better **UI consistency and readability**.  
2. **Validation Fix**  
- Removed **"Size or Quantity is required"** error when a valid value is entered.  
=> fix: size table ui fixed

components/Navbar/Navbar.tsx, components/ProductListingComponents/HorizontalFilterList.tsx/CustomerName.tsx, styles/components/horizontalFilter.module.scss
1. **Popup Added**  
- Displaying a **confirmation popup** when the **customer name** is successfully saved.  
=> Update: Customer Name Save Confirmation  

components/ProductListingComponents/FilterView/WebFilters.tsx, styles/globals.scss
1. **Search Icon Updated**  
- Replaced the **search icon** with a new design for better UI consistency.  
2. **Enter Key Functionality**  
- Enabled **search execution** when the **Enter** key is pressed for improved usability.  
=> Update: Search Enhancements  

components/Cart/CartListing.tsx
**Issue:**  
- When updating the **customer name**, an **empty string** was being set instead of triggering an error.  
**Solution:**  
1. Added validation to prevent **empty values** from being saved.  
2. Ensured an error message is displayed when the customer name is left blank.  
=> Bug Fix: Customer Name Updation  

components/OrderReport/OrderFilters.tsx, components/OrderReport/OrderReportTableMaster.tsx, components/Orders/ListingTable.tsx, styles/components/_listingTable.module.scss
1. **Filters Implemented**  
- Added filtering options to the **Order Listing** page for improved search and data refinement.  
2. **UI Improvements**  
- Enhanced the **user interface** for a cleaner and more intuitive experience.  
=> feat: filter section in order tables

components/ProductDetailComponents/ProductDetailDrawer/ProductDetailInfo.tsx
1. **Validation Added**  
- Prevented the **quantity field** from accepting **negative values** to ensure valid input.  
=> Quantity Field Validation  

components/Cart/CartListing.tsx, components/Cart/SizeQtyTable.tsx
1. **Delete Size Logic Updated**  
- Improved the logic for **removing sizes** from the **cart size table** for better functionality and accuracy.  
=> fix: size delete from cart logic changed

components/OrderReport/OrderFilters.tsx, components/OrderReport/OrderReportTableMaster.tsx, components/Orders/ListingTable.tsx, styles/components/_listingTable.module.scss
1. **Filters Implemented**  
- Added filtering options to the **Order Listing** page for improved search and data refinement.  
2. **UI Improvements**  
- Enhanced the **user interface** for a cleaner and more intuitive experience.  
=> Update: Order Listing Enhancements  

components/OrderReport/OrderReportLoadingSkeleton.tsx, components/Orders/ListingTable.tsx, components/Orders/OrderList.tsx, components/ProductDetailComponents/ProductDetailDrawer/ProductDetailInfo.tsx
1. **Sorting Feature Added**  
- Implemented **sorting options** in the **Order Listing** page for better data organization and usability.  
=> Update: Sorting in Order Listing  

cards/OrderDetailCard.tsx, components/Cart/CartListing.tsx, components/Cart/CartProductDetail.tsx, components/Cart/ClearCartModal.tsx, components/Cart/SizeQtyTable.tsx, components/Navbar/MobSideNavbar.tsx, components/Navbar/Navbar.tsx, components/OrderDetail/OrderDetail.tsx, components/ProductDetailComponents/ProductDetailDrawer/ProductDetailInfo.tsx, components/ProductListingComponents/ProductGridView/ProductsGridView.tsx, styles/components/cartProductDetail.module.scss, styles/components/navbar.module.scss, styles/components/orderDetail.module.scss
1. **UI Enhancements**  
- Improved overall **UI consistency and design** for a better user experience.  
2. **Loader Implementation**  
- Added **loaders** to all **action buttons** to indicate processing and improve responsiveness.  
=> Update: UI Improvements & Loaders  

components/CatalogListingComponents/CatalogListingMaster.tsx
1. **User Access Control**  
- Implemented **authorized user validation** on the **Catalog Listing** page to ensure only permitted users can access it.  
=> feat: user authentication added

components/Cart/CartListing.tsx, components/Cart/SizeQtyTable.tsx, components/Navbar/Navbar.tsx, components/ProductDetailComponents/ProductDetailDrawer/ProductDetailInfo.tsx
1. **UI Enhancements**  
- Improved the **Cart Page layout** for a more user-friendly experience.  
- Fixed **alignment, spacing, and responsiveness** issues.  
=> Update: Cart Page UI Fixes  

components/OrderReport/OrderFilters.tsx, components/Orders/ListingTable.tsx, components/ProductDetailComponents/ProductDetailDrawer/ProductDetailInfo.tsx
1. **New Filter Added**  
- Implemented **Purity** as a filter option in the **Order Listing** page for better search refinement.  
=> Update: Purity Filter in Order Listing

components/BulkOrder/CustomeMarketOrder.tsx, components/ProductDetailComponents/ProductDetailDrawer/ProductDetailInfo.tsx, components/ProductListingComponents/HorizontalFilterList.tsx/SortBy.tsx
1. **New Column Added**  
- Introduced a **Bulk Order** column in **Customer Market Orders** for better tracking.  
2. **Color Filter Update**  
- Added **Pink** as an option in the **color dropdown** under horizontal filters.  
=>  Update: Bulk Order & Color Filter Enhancements  

components/OrderReport/OrderFilters.tsx, components/Orders/ListingTable.tsx, components/ProductDetailComponents/ProductDetailDrawer/ProductDetailInfo.tsx
1. **New Filter Added**  
- Implemented **Purity** as a filter option in the **Order Listing** page for better search refinement.  
=> Update: Purity Filter in Order Listing  

components/BulkOrder/CustomeMarketOrder.tsx
1. **New Column Introduced**  
- Added **Color** field in the **Custom Market Order** table for improved product categorization.  
=> Update: Color Field Added  

components/Cart/CartProductDetail.tsx, components/Navbar/Navbar.tsx, styles/globals.scss
1. **Image Preview Feature Added**  
- Users can now **preview product images** directly on the **cart page** for better visibility.  
=> Update: Image Preview in Cart Page  

components/Cart/CartProductDetail.tsx
1. **Image Preview Feature Added**  
- Users can now **preview product images** directly on the **cart page** for better visibility.  
=> fix: preview image added

components/ARCBulkOrder/ARCBulkOrderMaster.tsx, components/ARCBulkOrder/CustomerOrderTable.tsx, components/ARCBulkOrder/InputFields.tsx, components/Cart/CartProductDetail.tsx, components/Navbar/Navbar.tsx, styles/globals.scss
1. **New Page Introduced**  
- Added a **new ARC Casting page** for better process management and workflow tracking.  
Let me know if any further refinements are required!  
1. **Image Preview Feature Added**  
- Users can now **preview product images** directly on the **cart page** for better visibility.  
=> Update: ARC Casting Page Added

components/ProductDetailComponents/ProductDetailDrawer/ProductDetailInfo.tsx, components/ProductDetailComponents/ProductDetails/ProductCode.tsx
1. **BOM Factory Code Added**  
- Now displayed on the **Product Detail Page** for better visibility and tracking.
=> Update: BOM Factory Code Added  

cards/ProductCard.tsx, components/ProductDetailComponents/ProductDetailDrawer/ProductDetailInfo.tsx, styles/components/productVariants.module.scss
- **Fixed text overlapping issue** in variant labels.  
- **Implemented sequential ordering** for custom product sizes.  
- Enhances UI readability and prevents layout issues.  
- Ensures a structured sequence for custom product sizes.  
- Ensure the UI fixes work across different screen sizes.  
- Validate that the ordering logic applies consistently.
=> Fixed Variants Text Overlapping & Sequenced Custom Product Sizes  

components/ProductDetailComponents/ProductDetailDrawer/ProductDetailInfo.tsx, components/ProductListingComponents/HorizontalFilterList.tsx/SortBy.tsx
- **Removed** the color **Rose** from the color dropdown.  
- **Added** the color **Pink** to the color dropdown.
=> Remove color rose and add pink

components/ProductDetailComponents/ProductDetailDrawer/ProductDetailInfo.tsx, components/ProductListingComponents/HorizontalFilterList.tsx/SortBy.tsx
- **Removed** the color **Rose** from the color dropdown.  
- **Added** the color **Pink** to the color dropdown.
=> fix: rose color removed and pink color added

cards/ProductCard.tsx
Fixed a bug in BOM code logic to ensure correct processing.
=> fix: bom code bug fixed

cards/ProductCard.tsx
fix: add validations on net wt
=> fix: add validations on net wt

components/ProductDetailComponents/ProductDetailDrawer/ProductDetailInfo.tsx, components/ProductDetailComponents/ProductDetails/ProductCode.tsx
Added BOM Code in product detail page
=> Added BOM Code in product detail page

cards/ProductCard.tsx, components/ProductDetailComponents/ProductDetailDrawer/ProductDetailInfo.tsx
feat: dynamic sizes and fields added to product detail
=> feat: dynamic sizes and fields added to product detail

cards/ProductCard.tsx, components/ProductDetailComponents/ProductDetailDrawer/ProductDetailInfo.tsx
- Dynamically added sizes from **Item Characteristics**
- Removed size dependency from **Category Size**
=> fix: dynamic item characteristics added

components/ProductDetailComponents/ProductDetailDrawer/ProductDetailDrawer.tsx
=> fix: variants glitch

components/ProductDetailComponents/ProductDetailDrawer/ProductDetailDrawer.tsx
fix: product detail api params fixed
=> fix: product detail api params fixed

components/ProductDetailComponents/ProductDetailDrawer/ProductDetailDrawer.tsx
- Updated frontend to handle API response changes after backend migration from **version 14 to version 15**.
=> version 14 to 15 migration changes
